name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - name: Set version outputs
        id: version
        run: echo "::set-output name=latest_tag::$(git describe --tags --abbrev=0)"

      - name: Check version outputs
        run: echo ${{ steps.version.outputs.latest_tag }}

      - name: set goversion outpout
        id: goversion
        run: echo "::set-output name=go_version::$(go version | sed -r 's/go version go(.*)\ .*/\1/')"

      - name: Check goversion outputs
        run: echo ${{ steps.goversion.outputs.go_version }}

      - uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: build docker image
        run: |
          docker build --build-arg VERSION=${{ steps.version.outputs.latest_tag }} --build-arg GOVERSION=${{ steps.goversion.outputs.go_version }} \
            -t ghcr.io/kunalsin9h/upkube:${{ steps.version.outputs.latest_tag }} .

      - name: push docker images
        run: |
          echo "${{ secrets.GHCR }}" | docker login ghcr.io -u "kunalsin9h" --password-stdin
          docker push ghcr.io/kunalsin9h/upkube:${{ steps.version.outputs.latest_tag }}
